# Docker file to run Mule Applications on a Linux based system

FROM java:openjdk-8-jdk

MAINTAINER vibhanshurt@gmail.com

#url to download mule runtime and application from artifact is a 
# build time parameter.
ARG mule_runtime
ARG mule_app

#install unzip functionality to unpackage mule runtime
RUN apt-get install --yes unzip

#download mule runtime
RUN cd ~ && wget $mule_runtime && echo "Downloaded successfully"
 
#unzip mule runtime to /opt/mule directory and delete original zip file.
RUN cd /opt && mkdir mule && unzip ~/mule*.zip -d mule && rm -rf ~/mule-*.zip && ls -ltr

RUN echo "list root dir files" && cd ~ && ls -ltr

#changing permissions for mule file to help start mule at runtime
RUN chmod -R 0755 /opt/mule

#copying mule application into mule apps folder
RUN cd /opt/mule/apps && wget $mule_app && ls

# Define environment variables.
ENV MULE_HOME /opt/mule

# Define mount points.
VOLUME ["/opt/mule/logs", "/opt/mule/conf", "/opt/mule/apps", "/opt/mule/domains"]

# Define working directory.
WORKDIR /opt/mule

CMD [ "/opt/mule/bin/mule" ]

# Default http port
EXPOSE 8081